### ISSUE TITLE
Json parse error with POST /log/search

### ISSUE THREAD

**Issue by spacer59** [amcgoogan/log-service#6]
I attempted to retrieve log file content using the `/log/search` endpoint but got an error response,

Body: `{
  "path": "/cribl.log",
  "keyword": "only",
  "limit": 4,
  "servers": [
    "localhost:8080",
    "localhost:8080"
  ]
}`

Headers: `content-type: application/json
Accept: application/x-ndjson`

Response: `There was an error parsing JSON data
Unexpected token { in JSON at position 992`

Note: Contents of `cribl.log` are not in json format, also I am able to retrieve contents with GET

**Comment by amcgoogan** [comment]
Its a little hard to see whats going on here.   The body should just be the the JSON object/envelope specified int the documentation:
'{ "path": "/cribl.log", "keyword": "only", "limit": 4, "servers": [ "localhost:8080", "localhost:8080" ] }'

Which works for me:
curl -d '{ "path": "/cribl.log", "keyword": "only", "limit": 4, "servers": [ "localhost:8080", "localhost:8080" ] }' -H 'Content-Type: application/json' localhost:8080/log/search

Is there extra JSON being sent with the 'Body: ' part you posted?

**Comment by amcgoogan** [comment]
I was initially thinking this was an issue with the request JSON, but if its the log file that log-service reads, it does not need to be in json format.  It should read it a line at a time and then add each line to a pojo, which gets transformed to json.  I guess it could be possible that there is something in the cribl.log file that is breaking the frameworks serialization process. 

If you add this logging to class: com.apm.log.service.services.DescendingOrderLogEventSearchService

```java
 return Flux.fromIterable(reader)
                .filter(l -> {
                    var result = filterChain.filter(l);
                    if(result.isStreamTerminated()) {
                        reader.end();
                    }
                    return result.isEventFiltered();
                })
                .map( l -> new SearchLogResult(hostname, l))
                .doFinally(s -> {
                    try {
                        reader.close();
                    } catch (Exception e) {
                        log.error("Error closing file", e);
                    }
                });
```
change the map section to this:

```java
 return Flux.fromIterable(reader)
                .filter(l -> {
                    var result = filterChain.filter(l);
                    if(result.isStreamTerminated()) {
                        reader.end();
                    }
                    return result.isEventFiltered();
                })
                .map( l -> {     //Change the map to this ->
                    log.info("Line:  {}", l);
                    return new SearchLogResult(hostname, l);
                })
                .doFinally(s -> {
                    try {
                        reader.close();
                    } catch (Exception e) {
                        log.error("Error closing file", e);
                    }
                });
```

is there a particular line it seems to break on?

**Comment by amcgoogan** [comment]
"There was an error parsing JSON data Unexpected token { in JSON at position 992"

Interestingly i tried to add these characters to log lines just to see what would happen, but it all seems to work fine.

**Comment by spacer59** [comment]
hmm interesting, I'm able to get results with the curl request as well. Possibly something wrong with my REST client.

**Comment by spacer59** [comment]
Tried without but still got the error. If curl is working this should be Ok for the sake of this assignment. I also used nd-json because I noticed it in the client request `accept(MediaType.APPLICATION_NDJSON)`
