### ISSUE TITLE
Security hack, ../path/to/file retrieves contents of the file

### ISSUE THREAD

**Issue by spacer59** [amcgoogan/log-service#7]
`GET http://localhost:8080/log/..%2Fcribl.log?limit=2&keyword=nothing` retrieves contents of file stored in `/var`. This essentially allows users to scan the entire file-system for unauthorized files.

**Comment by amcgoogan** [comment]
Ugh, i had this check in there but accidentally left it commented out (I was trying to get the unit test to send the get without modifying the '..' in the url).  

https://github.com/amcgoogan/log-service/blob/main/src/main/java/com/apm/log/service/controllers/requests/GetLogRequest.java

uncommenting and re-escaping.

**Comment by amcgoogan** [comment]
Uncommented the pattern matcher to check for dot dot.  Also, im not sure what my issue I was having when originally trying to unit test it, but it seems to be testing fine now for whatever reason.

https://github.com/amcgoogan/log-service/commit/37b7e89c3f4b824756553f2417cdacaba4034073
